name: crosswalk
channels:
  - nvidia
  - conda-forge
  - free
dependencies:
  - python=3.4
  - pip=9.0.1
  - pip:
    - tensorboard
    - tabulate
    - tqdm
    - pillow
    - notebook
    - jupyterlab
    - matplotlib
    - seaborn
    - ipywidgets
    - networkx
    - numpy
    - scikit-learn
    - pandas
    - pickle-mixin
    - gensim
    - scikit-learn-extra