name: fact2023
channels:
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10.6
  - pip=22.2.2
  - pip:
    - tensorboard==2.10.1
    - tabulate>=0.8.9
    - tqdm>=4.62.3
    - pillow>=8.0.1
    - notebook>=6.4.5
    - jupyterlab>=3.2.1
    - matplotlib>=3.4.3
    - seaborn>=0.11.2
    - ipywidgets>=7.6.5
    - networkx>=2.4
    - numpy>=1.24.1
    - scikit-learn>=1.2
    - pandas>=1.5.2
    - pickle-mixin
    - gensim>=4.3.0
    - scikit-learn-extra>=0.2.0